version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "@rails/actioncable" # we want to stay pinned to the 6.x branch for greater comaptability
        versions: ["7.x"]

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
