shared:
  project_name: Lookbook

  component_paths: [app/views]

  page_controller: "Lookbook::PageController"
  page_route: pages
  page_paths: [test/components/docs]
  page_extensions: [html.*, md.*]
  page_options: {}
  markdown_options:
    tables: true
    fenced_code_blocks: true
    disable_indented_code_blocks: true
    strikethrough: true
    highlight: true
    with_toc_data: true
    lax_spacing: true
  highlighter_options:
    theme: github
    dark: false

  sort_scenarios: false
  preview_paths: [test/components/previews]
  preview_display_options: {}
  preview_disable_action_view_annotations: true
  preview_type_default: view_component
  preview_controller: "Lookbook::PreviewController"
  preview_layout: ~
  preview_template: lookbook/previews/preview
  preview_inspector:
    panels: [source, notes, params, "*"]
  preview_embed:
    panels: false
    actions: [inspect, open]
    display_option_controls: true
    scenarios: []

  listen_paths: []
  listen_extensions: [rb, html.*]

  ui_theme: indigo
  ui_theme_overrides: {}
  ui_favicon: true

  log_level: 2
  log_use_rails_logger: true

  debug_menu: false
  experimental_features: false

development:
  debug_menu: true

test:
  debug_menu: true
