shared:
  hidden:
    label: Hidden status
    opts: {}

  label:
    label: Label
    opts: {}

  display:
    label: Display
    opts: {}

  priority:
    label: Priority
    opts: {}

  id:
    label: Id
    opts: {}

  component:
    label: Component
    opts: {}

  param:
    label: Param
    opts: {}

  logical_path:
    label: Logical Path
    opts: {}

  source:
    label: Source file
    opts: {}

  type:
    label: Preview type
    opts: {}
