permalink: pretty

template_engine: erb

defaults:
  - values:
      layout: "default"
      toc: []

# collections_dir: collections

collections:
  user_docs:
    output: true
    section: true
    permalink: /guide/:path.*
    title: User Guide

  dev_docs:
    output: true
    section: true
    permalink: /extend/:path.*
    title: Extending Lookbook

  api_docs:
    output: true
    section: true
    permalink: /api/:path.*
    title: API
