permalink: pretty

template_engine: erb

defaults:
  - values:
      layout: "default"
      toc: []

# collections_dir: collections

collections:
  guide:
    output: true
    section: true
    permalink: /guide/:path.*
    title: User Guide

  extend:
    output: true
    section: true
    permalink: /extend/:path.*
    title: Extending Lookbook
    label: Extending

  api:
    output: true
    section: true
    permalink: /api/:path.*
    title: API
