name: Lint

on: [pull_request]

jobs:
  trailing-whitespace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check for trailing whitespace
        uses: raisedevs/find-trailing-whitespace@restrict-to-plaintext-only
      - name: Check for merge conflicts
        run: git diff --check
        shell: bash
      - name: Ensure all files have newline at EOF
        uses: Logerfo/newline-action@0.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-build-rails-main-ruby-2.7-${{ hashFiles('**/Gemfile.lock') }}
      - name: Lint with Standardrb
        run: |
          bundle config path vendor/bundle
          bundle update
          bundle exec standardrb
        env:
          RAILS_VERSION: "~> 7.0.0"
